module.exports = [
  `https://www.allrecipes.com/recipe/22918/pop-cake/`,
  `https://www.allrecipes.com/recipe/6700/fabulous-homemade-bread/`,
  `https://www.bettycrocker.com/recipes/skillet-chicken-stroganoff/4966ef59-6380-49aa-89bf-5bf285b37a44`,
  `https://www.bonappetit.com/recipe/grilled-salmon-with-lemon-sesame-sauce`,
  `https://www.chowhound.com/recipes/slow-cooker-red-pepper-butternut-squash-soup-31117`,
  `https://www.cookinglight.com/recipes/grapefruit-campari-bars-shortbread-crust`,
  `http://www.eatingwell.com/recipe/259692/easy-chicken-cacciatore/`,
  `http://www.myrecipes.com/recipe/grapefruit-pound-cake`,
  `https://www.epicurious.com/recipes/food/views/iron-skillet-peach-crisp-56389711`,
  // add food52 here if I ever get it working
  `https://www.foodandwine.com/recipes/classic-southern-fried-chicken`,
  `https://www.foodnetwork.com/recipes/bobby-flay/perfectly-grilled-steak-recipe-1973350`,
  `https://www.foodnetwork.com/recipes/patrick-and-gina-neely/old-fashioned-macaroni-salad-recipe-1948708`,
  `http://www.geniuskitchen.com/recipe/sonic-strawberry-cheesecake-shake-122785`,
  `https://www.jamieoliver.com/recipes/eggs-recipes/amazing-yorkies/`,
  `https://www.thekitchn.com/recipe-watermelon-mint-frose-233904`,
  `https://www.simplyrecipes.com/recipes/grilled_salmon_with_peach_salsa/`,
  `https://www.seriouseats.com/recipes/2010/10/new-york-style-pizza.html`,
]
